[metadata]
name = analysis_helpers
version = attr: analysis_helpers.__version__
description = Helper classes, functions, and constants for running the analyses
author = Paxton C. Fitzpatrick and Jeremy R. Manning
author_email = contextualdynamics@gmail.com
url = https://github.com/ContextLab/memory-dynamics
download_url = https://github.com/ContextLab/memory-dynamics
license = MIT

[options]
# specific Python version installed in Docker container
python_requires = ==3.8.6
packages = analysis_helpers
setup_requires = setuptools>=38.3.0