# builds an image for running the notebooks to reproduce analyses and figures
# TODO: might need to do some sort of check to make sure submodules are initialized

FROM debian:bookworm-slim

LABEL maintainer="Paxton Fitzpatrick <Paxton.C.Fitzpatrick.GR@Dartmouth.edu>"

ARG DEBIAN_FRONTEND=noninteractive \
    notebook_ip=0.0.0.0 \
    notebook_port=8888 \
    notebook_dir="/mnt/code/notebooks" \
    develop=0

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    CONDA_DIR="/opt/conda" \
    MAMBA_NO_BANNER=1 \
    NOTEBOOK_IP="$notebook_ip" \
    NOTEBOOK_PORT="$notebook_port" \
    NOTEBOOK_DIR="$notebook_dir"
ENV PATH="${CONDA_DIR}/bin:${PATH}"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN --mount=type=bind,source=docker,target=/mnt \
    sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc && \
    # install basic system packages
    apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends eatmydata && \
    eatmydata apt-get install -y --no-install-recommends \
        bzip2 \
        ca-certificates \
        curl \
        git \
        vim-tiny && \
        # TODO: may need gcc and/or libc6-dev?
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    # symlink "vim.tiny" to just "vim" for simplicity
    ln -s /usr/bin/vim.tiny /usr/bin/vim && \
    # install conda & mamba (faster C++ reimplementation) via miniforge
    curl --progress-bar \
        -L "https://github.com/conda-forge/miniforge/releases/download/25.3.1-0/Miniforge3-25.3.1-0-Linux-$(uname -m).sh" \
        -o "$HOME/miniforge.sh" && \
    /bin/bash "$HOME/miniforge.sh" -bp $CONDA_DIR && \
    rm "$HOME/miniforge.sh" && \
    # configure conda for long-term stability/reproducibility
    mamba config --set auto_update_conda false && \
    mamba config --set notify_outdated_conda false && \
    mamba config --set channel_priority strict && \
    # reconstruct analysis environment from conda env spec
    mamba env update -f /mnt/analysis-environment.yml --prune && \
    mamba clean -afy && \
    # TODO: may want to do additional cleanup?:
    # find ${CONDA_DIR} -follow -type f -name '*.a' -delete && \
    # find ${CONDA_DIR} -follow -type f -name '*.pyc' -delete && \
    # TODO: likely need to pip-install some non-conda packages (e.g., hypertools, wordcloud, etc.)
    # pip install --disable-pip-version-check --no-cache-dir \
    #     hypertools \
    #     git+https://github.com/amueller/word_cloud.git<@some-hash> \
    #     etc... && \
    # TODO: install NTLK corpora/models/etc. (unclear if all of these are needed):
    # python -uBW ignore -m nltk.downloader \
    #     stopwords \
    #     averaged_perceptron_tagger \
    #     wordnet \
    #     punkt && \
    # TODO: install analysis_helpers package (note: NLTK stuff must be installed
    #  first if referenced at top level of helpers package)
    # pip install --disable-pip-version-check --no-cache-dir <path-to-analysis-helpers-package> && \
    # rm -rf <path-to-analysis-helpers-package> && \
    # rm -f "$HOME/nltk_data/*/*.zip" && \
    # copy in Jupyter notebook config file from build context
    mkdir -p "$HOME/.jupyter" && \
    cp /mnt/jupyter_notebook_config.py "$HOME/.jupyter/jupyter_notebook_config.py"
    # TODO: once image is finalized, remove not-needed apt packages:
    # apt-get purge -y --auto-remove \
    #     eatmydata \
    #     bzip2 \
    #     ca-certificates \
    #     curl \
    #     git \
    #     etc... && \

WORKDIR "/mnt"

ENTRYPOINT ["tini", "-g", "--"]

CMD ["jupyter", "nbclassic"]



